---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
library(leaflet)
library(geojsonsf)
library(sf)
library(htmlwidgets)
library(htmltools)

states = st_read("./data/location/tl_2020_us_state/tl_2020_us_state.shp", quiet = TRUE)
states = states %>% filter(!(STUSPS %in% c("PR", "AS", "GU", "MP", "VI", "HI", "AK")))
```

```{r}
#| echo: true
#| eval: true 
#| file: ./count.r
```

```{r}
head(n_offense)
```

```{r}
df = merge(states, n_offense, by.x = "STUSPS", by.y = "state_abb")
df = df %>% st_transform(4326)
```

```{r}
color_bin1 = colorBin("YlOrRd", domain = df$n_offense_22)
color_bin2 = colorBin("YlOrRd", domain = df$n_offense_21)
color_bin3 = colorBin("YlOrRd", domain = df$n_offense_20)
color_bin4 = colorBin("YlOrRd", domain = df$n_offense_19)
color_bin5 = colorBin("YlOrRd", domain = df$n_offense_18)

label1 = sprintf("<strong>%s</strong><br> %d", df$STUSPS, df$n_offense_22) %>% lapply(htmltools::HTML)
label2 = sprintf("<strong>%s</strong><br> %d", df$STUSPS, df$n_offense_21) %>% lapply(htmltools::HTML)
label3 = sprintf("<strong>%s</strong><br> %d", df$STUSPS, df$n_offense_20) %>% lapply(htmltools::HTML)
label4 = sprintf("<strong>%s</strong><br> %d", df$STUSPS, df$n_offense_19) %>% lapply(htmltools::HTML)
label5 = sprintf("<strong>%s</strong><br> %d", df$STUSPS, df$n_offense_18) %>% lapply(htmltools::HTML)

highlight = highlightOptions(weight = 5, color = "#666", dashArray = "", fillOpacity = 0.7, bringToFront = TRUE)

m = leaflet(df) %>%
    addTiles(group = "CartoDB.Voyager")

m %>%
    # 2022
    addPolygons(fillColor = ~color_bin1(n_offense_22),
    weight = 2, opacity = 1, color = "black", dashArray = "3", fillOpacity = 0.7,
    highlightOptions = highlight, label = label1, group = "2022") %>%
    addLegend(pal = color_bin1, values = ~df$n_offense_22, opacity = 0.7, title = "Offenses", position = "bottomleft", group = "2022") %>%
    # 2021
    addPolygons(fillColor = ~color_bin2(n_offense_21),
    weight = 2, opacity = 1, color = "black", dashArray = "3", fillOpacity = 0.7,
    highlightOptions = highlight, label = label2, group = "2021") %>%
    addLegend(pal = color_bin2, values = ~df$n_offense_21, opacity = 0.7, title = "Offenses", position = "bottomleft", group = "2021") %>%
    # 2020
    addPolygons(fillColor = ~color_bin3(n_offense_20),
    weight = 2, opacity = 1, color = "black", dashArray = "3", fillOpacity = 0.7,
    highlightOptions = highlight, label = label3, group = "2020") %>%
    addLegend(pal = color_bin3, values = ~df$n_offense_20, opacity = 0.7, title = "Offenses", position = "bottomleft", group = "2020") %>%
    # 2019
    addPolygons(fillColor = ~color_bin4(n_offense_19),
    weight = 2, opacity = 1, color = "black", dashArray = "3", fillOpacity = 0.7,
    highlightOptions = highlight, label = label4, group = "2019") %>%
    addLegend(pal = color_bin4, values = ~df$n_offense_19, opacity = 0.7, title = "Offenses", position = "bottomleft", group = "2019") %>%
    # 2018
    addPolygons(fillColor = ~color_bin5(n_offense_18),
    weight = 2, opacity = 1, color = "black", dashArray = "3", fillOpacity = 0.7,
    highlightOptions = highlight, label = label5, group = "2018") %>%
    addLegend(pal = color_bin5, values = ~df$n_offense_18, opacity = 0.7, title = "Offenses", position = "bottomleft", group = "2018") %>%
    # layer control
    addLayersControl(overlayGroups = c("2022","2021","2020","2019","2018"), options = layersControlOptions(collapsed = FALSE), position = "bottomright") %>%
    hideGroup(c("2021","2020","2019","2018"))
```